name: CI

on:
  pull_request:
    branches: [ "**" ]
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    needs: []
    services:
      sqlite:
        image: nouchka/sqlite3
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true
      - name: Install system deps
        run: sudo apt-get update && sudo apt-get install -y sqlite3 libsqlite3-dev netcat-openbsd
      - name: Stub Ollama
        run: nohup nc -lk 11434 &
      - name: Run specs
        run: bundle exec rspec
      - name: SSE smoke
        run: bundle exec rake sse:smoke
